
#  __  __  ____ _______ _____     _____ _
# |  \/  |/ __ \__   __|  __ \   / ____| |
# | \  / | |  | | | |  | |  | | | |    | |__   __ _ _ __   __ _  ___ _ __
# | |\/| | |  | | | |  | |  | | | |    | '_ \ / _` | '_ \ / _` |/ _ \ '__|
# | |  | | |__| | | |  | |__| | | |____| | | | (_| | | | | (_| |  __/ |
# |_|  |_|\____/  |_|  |_____/   \_____|_| |_|\__,_|_| |_|\__, |\___|_|
#                                                          __/ |
#                                                         |___/

# Enter the MOTDs that should be visible in the server list here:
# Yes, that's all..

motds:
  - "§a§lMOTD 1"
  - "§b§lMOTD 2"
  - "§9§lMOTD 3"
  - "§c§lMOTD 4"
